name: Release GUI to GitHub Releases

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build GUI
        run: |
          pyinstaller --onefile gui2.py

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/gui2.exe
